/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thisismyway.deadlockdetection;

import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class App {

    public static void main(String[] args) {
        Lock firstLock = new ReentrantLock();
        Lock secondLock = new ReentrantLock();

        FirstThread firstThread = new FirstThread(firstLock, secondLock);
        SecondThread secondThread = new SecondThread(firstLock, secondLock);

        new Thread(firstThread).start();
        new Thread(secondThread).start();
    }
}
